spring:
  datasource:
      url: jdbc:mysql://localhost:3306/it4045local?createDatabaseIfNotExist=true
      username: root
      password: password
  mvc:
    hiddenmethod:
      filter:
        enabled: true
